### ISSUE TITLE
Independent Class for Each Query Command

### ISSUE THREAD

**Issue by indrasaputra** [IndraGunawan/rubyq#2]
in current implementation, command such as `where`, `select`, or `order by` is located in one class.
imo, it will be better if each command is built somewhere. you can make a class for `where`, a class for `select`, etc.

hopefully, the implementation will be better and the query_builder class is not fat enough.

**Comment by IndraGunawan** [comment]
hi @indrasaputra, i don't see any advantage to make a standalone class for each clause statement because every method depent to other method to make a single query

**Comment by indrasaputra** [comment]
ok
